### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pym7857** [pym7857/meeting_app_flutter#2]
- [ ] geolocator 구현 (easy) (영민)
- [ ] 팀 구성 구현 (영민) 
- [ ] 채팅방 키워드로 왔다갔다 (영민)
- [ ] 인앱 결제 (영민)
- [ ] 아임포트 (성원)
- [ ] git 사용법 익히기 (성원)
- [ ] UI 여러가지 모듈 알아두기 (성원)
